### ISSUE TITLE
No checking for people that are both in the captain and players list

### ISSUE THREAD

**Issue by CodingRays** [luuknieuwdorp/community-queues#18]
People can be in the captains list and the players queue at the same time. No checking is done either when adding captains or when joining.

**Comment by ellienieuwdorp** [comment]
Yep, especially a big issue since the way the actual bot gets used is we add captains ourselves and users might get confused and try to !join too which would probably fuck everything up. (now that i think of this maybe this is why distribute broke when, I *think* mia joined using !join while she was already captain so this might be the bug we're looking for).

**Comment by CodingRays** [comment]
Just for reference mia did not join as captain. I also checked that no one else in the captain list joined the player list so this is most likely not related to #17 .
